### ISSUE TITLE
wrong labelling in elp-scatterplot-P0-Pk.html

### ISSUE THREAD

**Issue by pierreganty** [elenagutiv/Linearisation-2015#10]
Vertical axis should be labelled P0 instead of P2.
Horizontal axis should be labelled min(P1,P2).
Graph title should be rewritten to something more meaningful as well.

**Comment by elenagutiv** [comment]
Labelling issue is solved. I have also change the title: "Comparison of QARM'C Solving time before (P0) and after under-approximating (min(P1,P2))". Is it ok?

**Comment by pierreganty** [comment]
Yes, but QARMC (see #14)

**Comment by pierreganty** [comment]
Also, close the issue yourself when you have taken care of it. (And this is true for every issue)
