### ISSUE TITLE
File permissions (cont'd)

### ISSUE THREAD

**Issue by pierreganty** [elenagutiv/Linearisation-2015#16]
`run-tests.py` is executable while `run-tests-to-plot.py` is not.
I suspect that by setting them as **non** executable you would make progress toward solving #13. 
This is because you would have to execute `python file.py` to run the script and not have to worry
about where python is located. Note that I have not checked that this works.

**Comment by elenagutiv** [comment]
In fact, I execute run-tests.py typing in the command line:

python run-tests.py

And in the case of run-tests-to-plot.py, python 3 is required (as I use
TimeoutExpired exception when running elp procedure):

python3 run-tests-to-plot.py

Using this command you dont have to worry about where python is located
(and you dont need them to be executables so I should change that). I also
got the same error  when trying to run directly the script.

2015-11-24 11:38 GMT+01:00 pierreganty notifications@github.com:

**Comment by elenagutiv** [comment]
Actually both of them need to be run with python3 (that is the only way I
found to make the timeout to work properly). Once I have clear all the
instructions to run both scripts, and the answers to all the issues I will
tell you. That way is simpler to me and you :)

2015-11-24 12:41 GMT+01:00 Elena Gutiérrez Viedma elenagutiv@gmail.com:
