### ISSUE TITLE
merge run-tests-to-JSON.py and run-tests-to-plot.py

### ISSUE THREAD

**Issue by pierreganty** [elenagutiv/Linearisation-2015#19]
Looking at the two scripts they are extremely similar except for the following:

<img width="1211" alt="screen shot 2015-11-25 at 10 08 49 am" src="https://cloud.githubusercontent.com/assets/2111160/11393793/04f95a70-9362-11e5-838a-ae3288e18914.png">

Mustache takes a YAML file and YAML is a superset
of JSON. So I suggest to merge the two scripts into one and call it `run-tests-to-YAML.py`
(or a better name if you have one).  The `README.md` then explains plain text results in the YAML format will be generated somewhere and that from there one can generate nice graphs.

**Comment by elenagutiv** [comment]
Ok, so this new `run-tests-to-YAML.py` should still generate 2 output files: the one in the JSON format and more readable (which is the point of having this file) and the one in YAML format to generate the graphs?

**Comment by pierreganty** [comment]
If the YAML file is not less readable than the JSON file (for a human
being) then only keep the YAML one.

**Comment by elenagutiv** [comment]
YAML file is a one-line file (a very large one) with \ before every ". To
me it's quite annoying to read from there. But it's true that may be we
dont need to read it if we have the graphs.

2015-11-25 11:53 GMT+01:00 pierreganty notifications@github.com:

> If the YAML file is not less readable than the JSON file (for a human
> being) then only keep the YAML one.
>
