### ISSUE TITLE
scatter-plot: Use same scale in both axis

### ISSUE THREAD

**Issue by elenagutiv** [elenagutiv/Linearisation-2015#4]
Now, it adjusts each axis to the values that are actually plotted so it is not possible to see properly the relation between P1-time and P2-time.
Suggestion: May be plotting the ideal line (bisecting line) together with the rest of the points

**Comment by pierreganty** [comment]
SO to the rescue. Hopefully, these should help:
[adding a line to a chart](http://stackoverflow.com/questions/24497584/unable-to-horizontal-draw-reference-line-nvd3-bubble-chart)

[nvd3-setting-the-x-y-axis-values-to-line-chart-for-intervals](http://stackoverflow.com/questions/29740841/nvd3-setting-the-x-y-axis-values-to-line-chart-for-intervals)

[set-maximum-x-and-y-axis-range-nvd3](http://stackoverflow.com/questions/23833104/set-maximum-x-and-y-axis-range-nvd3)

[nvd3-d3-change-y-axis-minimum-value](http://stackoverflow.com/questions/17067595/nvd3-d3-change-y-axis-minimum-value)

**Comment by pierreganty** [comment]
Also consider to play with this JSFiddle website they are using because it is pretty convenient.
