### ISSUE TITLE
scatter-plot: Format of JSON data

### ISSUE THREAD

**Issue by elenagutiv** [elenagutiv/Linearisation-2015#5]
When I generate the JSON data file from the Pyhton script, json.dump gives a format which is not suitable by d3.json function unless I add commas between each result and '[',']' at the beginning and end of the file respectively.

See how to give proper format **automatically**.

**Comment by pierreganty** [comment]
SO to the rescue again. You might not get a single JSON but a stream of them as this [answer](http://stackoverflow.com/questions/26766840/comma-separator-between-json-objects-with-json-dump) suggests. So there is probably something wrong with the way you generate the JSON in the first place.
