### ISSUE TITLE
P0 vs min(P1,P2)

### ISSUE THREAD

**Issue by pierreganty** [elenagutiv/Linearisation-2015#8]
Produce a similar-looking graph comparing the time for P0 vs the best solving time for P1, P2.
This would tell us about the gain/cost of underaproximating in general.
Also the points with same answer and different answer should have different labels.

**Comment by elenagutiv** [comment]
Now points are shown using 4 different shapes (though it is not very visible right now):
P1:passed, P2:passed -> circle
P1:passed, P2:failed-> triangle up
P1:failed, P2: passed -> triangle down
P1:failed, P2:failed -> square.

This can be simplified to same answer: shape 1, different answer: shape 2. May be it is simpler (I will add a key to explain meaning of shapes).

It also could be a good idea to change the scale of both axis (as there is a thick cloud of points near (0,0) and then points far away from there), may be logarithmic scale could be a good option. What do you think?

**Comment by elenagutiv** [comment]
Actually....we should not see points with triangle shape when representing P1 and P2, therefore I will use 1 shape.

**Comment by elenagutiv** [comment]
In fact, there are not points in the plot (P1 vs P2) with different answer. Sorry for that, i will change it

**Comment by pierreganty** [comment]
Implemented as of 6e341828e06f73099c3c0bb5ab0b96cd3465af38
