### ISSUE TITLE
Problem in displaying graph

### ISSUE THREAD

**Issue by pierreganty** [elenagutiv/Linearisation-2015#9]
As you can see in the attached screenshot:

<img width="1390" alt="screen shot 2015-11-23 at 11 31 14 am" src="https://cloud.githubusercontent.com/assets/2111160/11334504/c576c4a6-91d5-11e5-9f7a-5f0262c35d26.png">

When hovering above a data point, the vertical line is not reaching all the way up to the point.
On the other hand, the horizontal line is perfectly fine. This happened both in Firefox and Safari.

**Comment by pierreganty** [comment]
Actually, the horizontal line is **not** fine either. It is too long since it reaches the point and continues.

**Comment by elenagutiv** [comment]
It might be related with changing the scale, as this did not happen before changing it
